# Generated by Django 3.2.8 on 2021-10-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrations', '0001_initial'),
        ('comments_rating', '0001_initial'),
        ('core', '0002_alter_ponto_turisticos_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='Attrations',
            field=models.ManyToManyField(to='attrations.attrations'),
        ),
        migrations.AddField(
            model_name='ponto_turisticos',
            name='Comments',
            field=models.ManyToManyField(to='comments_rating.comments'),
        ),
    ]
