# Generated by Django 3.2.8 on 2021-10-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20211028_2054'),
        ('core', '0003_auto_20211026_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='Rating',
            field=models.ManyToManyField(to='rating.rating'),
        ),
    ]
