# Generated by Django 3.2.8 on 2021-10-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizations', '0002_alter_localization_adress'),
        ('core', '0004_ponto_turisticos_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='Adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizations.localization'),
        ),
    ]
