# Generated by Django 3.2.8 on 2021-11-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ponto_turisticos_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turisticos',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_pontos_turísticos'),
        ),
    ]
